### ISSUE TITLE
[Discussion] Sponsorblock integration, and the new naming scheme

### ISSUE THREAD

**Issue by TheFrenchGhosty** [TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts#1]
>Copied from https://gitlab.com/TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts/-/issues/5

"SponsorBlock is an extension that will skip over sponsored segments of YouTube videos. SponsorBlock is a crowdsourced browser extension that lets anyone submit the start and end times of sponsored segments of YouTube videos. Once one person submits this information, everyone else with this extension will skip right over the sponsored segment." https://sponsor.ajay.app/ / https://github.com/ajayyy/SponsorBlock

In November 2019, Sponsorblock was ported to MPV by [po5 / Eva](https://github.com/po5): https://github.com/po5/mpv_sponsorblock.

Last week, I opened an [issue](https://github.com/po5/mpv_sponsorblock/issues/5) to ask him-her to add support for local files, after [1c213b2](https://github.com/po5/mpv_sponsorblock/commit/1c213b297e5c6751be5271d67374043ba0b6b01e) support is now added, and users can now add a custom naming scheme to the implementation.

At first my idea was to just add the usual youtube-dl implementation of video IDs into titles ([Title]-[VideoID].[ext]), but as pointed by po5 [here](https://github.com/po5/mpv_sponsorblock/issues/5#issuecomment-584486731) "it could leak info for files with scene naming".

This is why I'm posting this today, I want your opinion:

What naming scheme do you want for the video IDs?

- Default youtube-dl (causing the leak of information to Sponsorblock in case you open files with scene naming in MPV)

- The idea I had [here](https://github.com/po5/mpv_sponsorblock/issues/5#issuecomment-584634959) " - ID=[VIDEOID].ext" at the end of every file (example: Uploader/Uploader - 20191231 - Title/Uploader - 20191231 - Title - ID=VideoID.ext)

- Something else?

Note: Obviously this will make the scripts go to a V2.0 (and everything will need to be redownloaded... sorry), but it's needed anyway since I noticed that the ```--format``` is incomplete and doesn't properly support 1440p-2160p-4320p (right now 1080p will be chosen instead if it's the only source for av01 or vp9.2). See the [TODO list](https://gitlab.com/TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts#todo-in-this-order) for the other things that will change.

---

You can comment here or on [Reddit](https://redd.it/f40vds), please don't post the same ideas multiple times, just thumbs up (upvote on Reddit) the one you like the most (and comment if you have anything to add).

**Comment by TheFrenchGhosty** [comment]
The implementation will be "[VIDEOID].ext" because of https://github.com/ankenyr/jellyfin-youtube-metadata-plugin

**Comment by po5** [comment]
` [VIDEOID].ext` will leak CRCs in anime-style naming which is arguably worse than scene groups, but it doesn't matter as long as you use an autoprofile to apply local file matching on relevant directories.

This would be the lua pattern needed for mpv_sponsorblock `" %[([%a%d%-_]+)%].[mw][kpe][v4b]m?$"`

**Comment by TheFrenchGhosty** [comment]
@po5 I actually didn't think about that, I guess the use case is really small so it's not that big of a problem, especially if the pattern you sent fixes the issue.

**Comment by po5** [comment]
To clarify, it doesn't fix anything. Just wanted to provide a pattern for the new naming scheme.
Use [auto-profiles.lua](https://github.com/wiiaboo/mpv-scripts/blob/master/auto-profiles.lua) with something like
```
[local_sponsors]
profile-desc=cond:string.match(p.working_directory, "TheFrenchGhostys-YouTube-DL-Archivist-Scripts")~=nil
script-opts=sponsorblock-local_pattern= %[([%a%d%-_]+)].[mw][kpe][v4b]m?$

**Comment by po5** [comment]
The script now makes sure the detected ID is 11 characters long, will no longer leak CRCs.
https://github.com/po5/mpv_sponsorblock/commit/6a64faf8dc5d7b239ae84fff479b8c3037a31ad1

It can still leak parts of unrelated filenames but it's now much less likely.
