### ISSUE TITLE
Issue with thumbnail embedding

### ISSUE THREAD

**Issue by edo0** [TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts#16]
When I run the scripts, be it for "Archive" or "Active" videos, I always end up with this error (this aside, all the rest works fine)

```
ERROR: Only mp3 and m4a/mp4 are supported for thumbnail embedding for now.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2065, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/lib/python3.8/site-packages/youtube_dl/postprocessor/embedthumbnail.py", line 91, in run
    raise EmbedThumbnailPPError('Only mp3 and m4a/mp4 are supported for thumbnail embedding for now.')
youtube_dl.postprocessor.embedthumbnail.EmbedThumbnailPPError: Only mp3 and m4a/mp4 are supported for thumbnail embedding for now.
```
OS is Arch Linux, and all software is up to date [`youtube-dl 2020.06.16.1-1`]

**Comment by edo0** [comment]
The thumbnail is downloaded in the folder in .webp format, if that can have anything to do with this error

**Comment by TheFrenchGhosty** [comment]
>ERROR: Only mp3 and m4a/mp4 are supported for thumbnail embedding for now.

Everything is normal.

From the ReadMe:

`--embed-thumbnail : Tell youtube-dl to embed thumbnail in the audio as cover art (only useful when downloading audio-only content like podcast).`
