### ISSUE TITLE
[Enhancement] Adding option to trim sponsor segments out of videos

### ISSUE THREAD

**Issue by edo0** [TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts#17]
Would it be possible to implement this as an optional feature, possibly integrating some of the ready-make code from [SponSkrub](https://github.com/faissaloo/SponSkrub)?
I understand this would not be popular with everyone (as opposed to archiving unaltered content), but I think many would find this addition useful, considering it possibly is just a step away from being implemented.
Hope you will consider it!
Thank you in advance for all the work you have done up to now, your scripts rock!!

**Comment by TheFrenchGhosty** [comment]
I don't want to change the content in ANY way, the sponsor is part of the content, and the Sponsorblock data aren't perfectly accurate. MPV_Sponsorblock is usable with it so I don't see a problem.

**Comment by Michilious** [comment]
@edo0 You can add `--sponsorblock-remove all` somewhere at the end of whatever .sh file you want. 
I did it between `--throttled-rate 100K` and `--batch-file` in the example of Unique.sh
