### ISSUE TITLE
Issues with downloading on Windows 10

### ISSUE THREAD

**Issue by alex1651** [TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts#18]
First of all, thanks for the hard work that you have put into these scripts.

I have a folder called YoutubeDL on my D: drive and copied the Active, Archive and Watch folders into my YoutubeDL folder and copied a link and pasted it into the Sources.txt file in the Unique folder under Active Scripts and then shift+right click in the folder and select open PowerShell Window here and then call Unique.ps1 and get the message from the first attached screenshot, so i set the execution policy using "Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass" and then call Unique.ps1 again and get " youtube-dl : The term 'youtube-dl' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At D:\YoutubeDL\Active Scripts\Unique\Unique.ps1:9 char:1
+ youtube-dl --format "(bestvideo[vcodec^=av01][height>=4320][fps>30]/b ...
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (youtube-dl:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException"

I believe i am missing something simple. If you could show me what i am doing wrong, i would greatly appreciate it.

This is the video URL that i am using as a test: https://www.youtube.com/watch?v=zkL2RGB8W7Q

![YoutubeDL script execution policy issue](https://user-images.githubusercontent.com/15963866/86041209-8b6b7e00-ba02-11ea-9e41-5844bd0af940.png)

![YoutubeDL script after applying execution policy](https://user-images.githubusercontent.com/15963866/86041322-b950c280-ba02-11ea-96a3-72a4dddc5798.png)

**Comment by TheFrenchGhosty** [comment]
This isn't caused by the script. You need to add youtube-dl to your path.
