### ISSUE TITLE
[Question] Handling of new Subtitles

### ISSUE THREAD

**Issue by edo0** [TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts#19]
As per the title, I was wondering how the script, especially the "Active" category, handles newly-uploaded subtitles for already-downloaded videos.
Are those downloaded and muxed automatically, or if not, would there be a chance to implement something like that?

**Comment by TheFrenchGhosty** [comment]
Subtitles are downloaded when the script is ran, there is no way to download new subtitles at a later date.

If you want to have most of them, feel free to just run archive scripts instead of merging the content of active into it.
