### ISSUE TITLE
[Windows] Path length issue

### ISSUE THREAD

**Issue by myangelaku** [TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts#24]
(Channel scripts, happens both in archive&active scripts) 
`[download] Downloading video 14 of 261
[youtube] MspNRp2uO3A: Downloading webpage
WARNING: video doesn't have subtitles
[info] Writing video description to: Dr Levi Harrison\Dr Levi Harrison - 20180815 - The Dr. Levi Show #115 - Jesse Nicassio, Juke Performance Inc#\Dr Levi Harrison - 20180815 - The Dr. Levi Show #115 - Jesse Nicassio, Juke Performance Inc. [MspNRp2uO3A].description
ERROR: Cannot write description file Dr Levi Harrison\Dr Levi Harrison - 20180815 - The Dr. Levi Show #115 - Jesse Nicassio, Juke Performance Inc#\Dr Levi Harrison - 20180815 - The Dr. Levi Show #115 - Jesse Nicassio, Juke Performance Inc. [MspNRp2uO3A].description
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 1785, in process_info
FileNotFoundError: [Errno 2] No such file or directory: 'Dr Levi Harrison\\Dr Levi Harrison - 20180815 - The Dr. Levi Show #115 - Jesse Nicassio, Juke Performance Inc#\\Dr Levi Harrison - 20180815 - The Dr. Levi Show #115 - Jesse Nicassio, Juke Performance Inc. [MspNRp2uO3A].description'`

**Comment by TheFrenchGhosty** [comment]
From the readme:


>Warning for Windows users: Because Windows is using a path length limit of 260 characters, you might have problems when downloading videos with long title (or even videos with short one if your path is long), supposedly there is ways to disable this limit but during my testing I couldn't make it to work. Using C:\YouTube-DL\ *should* work.
