### ISSUE TITLE
Consider moving to a youtube-dlc

### ISSUE THREAD

**Issue by TheFrenchGhosty** [TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts#26]
YouTube-DL has been in maintenance mode for years, with little to no work. Lately development slowed even more.

A new fork named "[youtube-dlc](https://github.com/blackjack4494/youtube-dlc)" just came out, dedicated to merging as much PR as possible (youtube-dl has MORE THAN 700 OPEN PR).

It's maybe a good idea to move to it, but I want to wait to see if it's maintained and not abandoned after a month.

I'm looking forward to people opinion about this.

Related: https://github.com/bibanon/tubeup/issues/129

**Comment by TheFrenchGhosty** [comment]
My scripts will move to youtube-dlc if the maintainer is still working on it in November.

**Comment by koutsie** [comment]
Sounds good!
