### ISSUE TITLE
Output stdout and stderr to log file

### ISSUE THREAD

**Issue by bcmryan** [TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts#27]
This is a great project that I've finally got around to playing with. I do, however, have one suggestion regarding the use of a log file for stdout and stderr. If the point of this project is to have downloading in the background, it would only make sense to me to be able to go back to look at the output if needed. I personally ran into this today when my wireless internet disconnected, leaving me unsure what the status of my download was, as my terminal emulator filled up with error messages too long to scroll back to the download that was in progress during the disconnect.

Luckily, a simple `2>&1 | tee -a output_$(date +%Y%m%dT%H%M%SZ).log` appended to the end of each script will output a log file with the date and time and will allow all data to still be seen in the terminal emulator. I personally will keep all dated log files instead of having a output.log file that would be continually overwritten. I understand that such a large number of log files might be a bit unpleasant to other users, so, in that case, I would also recommend a simple log folder for the output files (and potentially even archive.log) to keep things tidy.

**Comment by TheFrenchGhosty** [comment]
This is a great idea. I will surely add that when I'll work on it again

**Comment by TheFrenchGhosty** [comment]
Done in https://github.com/TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts/commit/688ebcda9c21cedf799fdadb8acaeb6d17c74161
