### ISSUE TITLE
Max Path Length Limit on Windows

### ISSUE THREAD

**Issue by tyablix** [TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts#28]
Under Windows, there is the MAX_PATH limitation (max path length of 260 chars) which in Windows 10/Server 2016+ can be "disabled" using regedit or group policy. However, in my experience, neither of these actually change anything and I still run into "No such file or directory" Python path errors using either youtube-dl or dlc, even when downloading at the root of a drive for some videos with long titles.

I've commented on the issue for the yt-dlc repo but I thought I'd add what I said here while it's still a problem some may face.

A fix is to use `\\?\C:` notation at the beginning of the output string. E.g:

`"\\?\C:\%(uploader)s/%(uploader)s - %(upload_date)s - %(title)s/%(uploader)s - %(upload_date)s - %(title)s [%(id)s].%(ext)s"`

You can put any path you like after the `C:`.

This allows for any video to be downloaded regardless of the path length by telling the Windows APIs to no longer parse the path in the same way. More info [here:](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#win32-file-namespaces)

It might be beneficial to others to mention something about path lengths in the readme for those running into this annoying Windows limitation.

P.S. Great work on the scripts :)

**Comment by VADemon** [comment]
Each individual name (file, folder, in the hierarchical structure) still cannot be longer than the filesystem limit ("255 UTF-16 code units").

Has this been brought up with ydl / ydlc yet?

**Comment by tyablix** [comment]
There is an [open issue](https://github.com/blackjack4494/yt-dlc/issues/242) regarding filename length errors on the ytdlc repo so hopefully something comes of that soon.

**Comment by 93-infinity** [comment]
For what it's worth WSL seems to be able to manipulate files with windows-illegal characters or long paths, and I have been using the linux script in WSL.

**Comment by TheFrenchGhosty** [comment]
The scripts moved to WSL, this issue is therefore not a problem anymore.

https://github.com/TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts/commit/ad693126fbddce28b62cd069fe5725eac6b9450d
