### ISSUE TITLE
Add a way to handle livestreams currently running

### ISSUE THREAD

**Issue by floriplum** [TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts#34]
I noticed that when i add a currently running livestream, to my sources with the Active Unique Script, that the Video is downloaded up till the point where im at the current time. After that the video is finished and after rerunning the script it obviously wont get downloaded again since it is already existing and in the archive list.

I know that this may be some Youtube-dlc limitation, but if there is a optio,n to somehow work around, it would be useful to add it to the script. 
I didn't found a flag that would handle livestreams better, but i haven't really looked into it. When i just run youtube-dlc -f <format> <url> the stream is downloading just fine as it is going on.

I will look into the youtube-dlc options again, but maybe someone already knows how to handle livestreams.

**Comment by TheFrenchGhosty** [comment]
Youtube-dl / youtube-dlc don't handle ongoing livestreams properly.

Use streamlink.

**Comment by floriplum** [comment]
That's why i opened this "issue", because ongoing live streams aren't handled properly.
When i run the active script and one of the channels is streaming i end up with a unfinished stream that is ignored due to the archive log.

After a bit research it appears that `--match-filter '!is_live & !live'` should be able  to ignore live streams. This way the stream would get downloaded when it is finished.  
This may need a bit more testing since im not 100% sure if it catches all the YouTube live streams. But i think it would be good to add a way to ignore live streams until they are finished.
