### ISSUE TITLE
Getting rate limited without even downloading videos

### ISSUE THREAD

**Issue by Hawpe** [TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts#39]
When attempting to download a large channel's videos (> 1100 videos), I get rate limited using the 'Active Scripts' because so few of the videos are actually from 2021 compared to all other ones. `yt-dlc` downloads the first 10 or so videos correctly because they're the most recent ones, then it continues with the remaining videos, checks their date and skips them without ever sleeping causing the IP to get rate limited.

Is there any way to avoid this? Shouldn't the script assume when you're downloading a channel that videos are sorted by their upload date and stop as soon as a video is out of the date range?

**Comment by TheFrenchGhosty** [comment]
Your IP is blacklisted. Use another one.

**Comment by Hawpe** [comment]
Uh yeah that's fairly obvious. That doesn't solve the source of the problem. Getting another IP and doing the same thing will result in that IP being blacklisted as well because the script opens every video to check for its date without ever sleeping. It only sleeps between downloads, not between the requests to the videos themselves. This results in hundreds of videos being checked within a few minutes.
