### ISSUE TITLE
So many random videos are just not downloading

### ISSUE THREAD

**Issue by Rings4** [TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts#40]
I'm not sure what's going on. I'm getting this issue with the Channel Archive script as well as Playlist Archive script. It just doesn't download anything for several vids. For some vids, it downloads a bunch of .vtt files, but still no video. Re-running the .ps1 file doesn't get the missing videos. What can I do to fix this?

I'm on Windows, with up-to-date youtubedl and ffmpeg (installed via chocolatey), and my path is X:\YouTube-DL\

Here's a playlist I'm trying to archive: https://www.youtube.com/playlist?list=PL6EC7B047181AD013
Some videos that don't download from this playlist include Episodes 57-60 (parts 1-3 and epilogue). There are more that don't download.

There's also the issue of many fragments being "lost" or not downloading, causing in the final video to freeze at a particular frame for a few seconds while the audio continues playing normally before finally picking back up.

![Screenshot 2021-02-07 16 37 56](https://user-images.githubusercontent.com/32050292/107160209-dbc89800-6962-11eb-8257-b24cd63bb908.png)

**Comment by Rings4** [comment]
Update: it seems changing my path to just X:\A\ shortened the directory names just enough for the missing episodes to download. I guess the suggested path in the readme was still too long. 

Unfortunately, some videos still fail to download because their names are just too long. Any chance you can make the names just cut off once a certain combined character limit is reached for the entire path+file?

**Comment by TheFrenchGhosty** [comment]
Path length issue. I can't do anything about it.

**Comment by Rings4** [comment]
> 
> 
> Path length issue. I can't do anything about it.

Actually, I found a solution. In order to limit path names, you can add ".40s" etc. to limit it to 40 characters. What I did was get rid of the redundant info (channel name doesn't need to be in the base path, video subfolder AND video filename, so I deleted it in the last two) and then limited the title to 40 characters. This limit can then be shortened on a second run to grab missed videos, if any.

I really think you should at least mention this somewhere people would see so they don't just conclude your scripts don't work on Windows, because it's a very simple fix.
