### ISSUE TITLE
Channel Archive scripts downloading videos from playlists for some reason

### ISSUE THREAD

**Issue by Rings4** [TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts#41]
I don't see why this should occur. I don't want any videos from playlists that aren't by the channel. When I want to archive a channel, I was JUST that channel. Not the random videos they add to their "favourites" playlist that has nothing to do with their content. A channel with a couple dozen vids has hundreds of playlisted videos that I now have to go through and delete.

If it's possible to ignore playlisted videos, please let me know.

**Comment by TheFrenchGhosty** [comment]
Don't add a playlist link. The scripts only download what you add, and won't download playlists if you add channels.

**Comment by Rings4** [comment]
> 
> 
> Don't add a playlist link. The scripts only download what you add, and won't download playlists if you add channels.

I'm not adding a playlist link though? I'm adding a channel link. Here is a channel that gets me 5x more videos from playlists than from the channel: https://www.youtube.com/user/AntiRivet

All channels get playlisted videos. I want channels to not do that.

**Comment by github-account1111** [comment]
I think I've run into this problem before. Try adding `/videos` to the end of that channel url.

This has nothing to do with script functionality.
