### ISSUE TITLE
Add a Filter to ignore ongoing Livestreams

### ISSUE THREAD

**Issue by floriplum** [TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts#42]
Since Youtube-DL(or whatever fork we decide to use) doesn't really handle ongoing Livestreams very well, i think it would be a good idea to filter out Livestreams that are currently running.  
The filter `--match-filter '!is_live & !live'` should work for YouTube, to filter out ongoing streams.

I hate to be the guy that opens a duplicated ticket about something that was already closed, but i think i did a bad job describing my problem. Anyway here is the closed ticket #34.

Im open to discuss if there is a better way to filter out running stream and if it is a good idea in the first place.
But if it is decided to add the filter i can open a PR to add it to the active 

Greetings,
Florian

**Comment by TheFrenchGhosty** [comment]
I will definitely implement that.

Sorry I closed the previous issue, I often just quickly read them, without really trying to understand the issue.

**Comment by floriplum** [comment]
No Problem, it was mostly my fault since i did a bad job describing my issue.

**Comment by TheFrenchGhosty** [comment]
Done in https://github.com/TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts/commit/30958d3dbfad89580bdedf2bf5ffcf7dc92922bf
