### ISSUE TITLE
Archive Channel script fails after 30 videos

### ISSUE THREAD

**Issue by Rings4** [TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts#43]
_I'd like to archive a channel that does daily uploads, but that's impossible because apparently the script fails once it skips 30 videos due to being too recent._

_I've changed the date format to --datebefore "$($(get-date -Format yyyy))0201" but now I'll have to delete the videos posted in 2021 and remove them them in the archive.log._

It appears the issue isn't the skipped videos. This channel simply does not go through more than 30 videos for some reason, and I don't know why.

The channel in question I'm experiencing this issue with is Game Grumps. The following 2 urls produce the same issue.

https://www.youtube.com/user/GameGrumps
https://www.youtube.com/user/GameGrumps/videos

Apologies if I'm providing the wrong type of url. Please let me know how I can get the proper channel url if that is the case.

**Comment by TheFrenchGhosty** [comment]
Tested, works for me.

**Comment by Rings4** [comment]
> 
> 
> Tested, works for me.
> 
> ```
> [download] 2021-01-01 upload date is not in range 0001-01-01 - 2020-12-31
> [download] Downloading video 60 of 7495
> [youtube] VL2PlLTZpUM: Downloading webpage
> [debug] Sort order given by user: 
> [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9(9), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
> [info] Downloading format(s) 399+251
> [download] 2021-01-01 upload date is not in range 0001-01-01 - 2020-12-31
> [download] Downloading video 61 of 7495
> [youtube] ImmkZqyFa7w: Downloading webpage
> [debug] Sort order given by user: 
> [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9(9), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
> [info] Downloading format(s) 303+251
> [info] Writing video description to: GameGrumps/GameGrumps - 20201231 - Clear eyes. Full tarp. Can't ruse. - Danganronpa/GameGrumps - 20201231 - Clear eyes. Full tarp. Can't ruse. - Danganronpa [ImmkZqyFa7w].description
> WARNING: There are no annotations to write.
> [info] Writing video metadata as JSON to: GameGrumps/GameGrumps - 20201231 - Clear eyes. Full tarp. Can't ruse. - Danganronpa/GameGrumps - 20201231 - Clear eyes. Full tarp. Can't ruse. - Danganronpa [ImmkZqyFa7w].info.json
> [youtube] ImmkZqyFa7w: Downloading thumbnail ...
> [youtube] ImmkZqyFa7w: Writing thumbnail to: GameGrumps/GameGrumps - 20201231 - Clear eyes. Full tarp. Can't ruse. - Danganronpa/GameGrumps - 20201231 - Clear eyes. Full tarp. Can't ruse. - Danganronpa [ImmkZqyFa7w].webp
> [debug] Invoking downloader on 'XXXX'
> [download] Sleeping 24.79 seconds...
> ```

That's really strange. Which url did you use? I've resorted to scraping all the urls off youtube via the extension downthemall and simply feeding the script each individual url, but am curious what you did different to make it work for you for future reference.

**Comment by TheFrenchGhosty** [comment]
I used https://www.youtube.com/user/GameGrumps
