### ISSUE TITLE
Watch on Mobile Devices script is still broken...

### ISSUE THREAD

**Issue by TheFrenchGhosty** [TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts#9]
The change used to fix #7... actually changed *something* and now it doesn't download 1080p video but just get 720p...

It doesn't make sense... the syntax is correct, something is wrong.

**Comment by po5** [comment]
Because you can't expect the `avc1` video codec for youtube, it's `avc1.4d400c`, `avc1.4d4015`, `avc1.4d401e`, `avc1.4d401f`, `avc1.640028`, `avc1.64002a` and so on.
Change it to `[vcodec^=avc1]`.

**Comment by TheFrenchGhosty** [comment]
> Because you can't expect the `avc1` video codec for youtube, it's `avc1.4d400c`, `avc1.4d4015`, `avc1.4d401e`, `avc1.4d401f`, `avc1.640028`, `avc1.64002a` and so on.
> Change it to `[vcodec^=avc1]`.

Interesting... so that's what ```^``` is for. I couldn't find any information about it.

Thanks.

**Comment by po5** [comment]
It works similarly to css selectors, if that helps.

I'd like to add the `--format` in your main scripts is way too long for what you're trying to do.
I'd understand if your idea required enumerating all possibilities, like wanting 720p60 over 1080p30, but that's just not the case here.

You can take advantage of the fact that for any given format, YouTube will give more bitrate to a higher resolution stream of the same format.
`--format "(bestvideo[vcodec^=av01][fps>30]/bestvideo[vcodec=vp9.2][fps>30]/bestvideo[vcodec^=vp9][fps>30]/bestvideo[fps>30]/bestvideo[vcodec^=av01]/bestvideo[vcodec=vp9.2]/bestvideo[vcodec^=vp9]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)/best"`

Also, your current format selection will avoid AVC at any cost which seems pretty weird to me, so I made it possible for it to be selected if it really is the best format.

Hope this helps, feel free to use it if you think I raised good points.

**Comment by po5** [comment]
From my own comparisons, YouTube's HDR av1 streams are worse than vp9.2 (worse than SDR vp9, even).
SDR av1 formats are named something like `av01.0.08M.08` and HDR like `av01.0.08M.10.0.110.09.16.09.0`.
This would be the revised format selection:
`--format "(bestvideo[vcodec=vp9.2][fps>30]/bestvideo[vcodec^=av01][vcodec!$=.0][fps>30]/bestvideo[vcodec^=vp9][fps>30]/bestvideo[vcodec^=av01][fps>30]/bestvideo[fps>30]/bestvideo[vcodec=vp9.2]/bestvideo[vcodec^=av01][vcodec!$=.0]/bestvideo[vcodec^=vp9]/bestvideo[vcodec^=av01]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)/best"`

Unfortunately, youtube-dl doesn't support filering by the same metadata field twice, as is apparant with
`youtube-dl --format "bestvideo[vcodec^=vp][vcodec!=.]" https://www.youtube.com/watch?v=6TOEWPDrnwQ`
(downloads vp9.2)

Will file an issue over there and hopefully get this fixed.

**Comment by TheFrenchGhosty** [comment]
>I'd like to add the --format in your main scripts is way too long for what you're trying to do.
I don't think there is a need to enumerate all possibilities here.

I want it to never break, I think it's a good way to do it. Your solution will work for YouTube, but won't necessarily for bad websites.

>Also, your current format selection will avoid AVC at any cost which seems pretty weird to me, so I made it possible for it to be selected if it really is the best format.

You're right, I forgot to add it when I rewrote the --format from scratch.

>From my own comparisons, YouTube's HDR av1 streams are worse than vp9.2 (worse than SDR vp9, even).

Mmh, I never compared the av1 streams to the others. I believe you but I guess since it's a "new" format it might still be good to use it. I don't really know.

**Comment by po5** [comment]
Don't know if this is the best place to continue this conversation but my thoughts:

> Your solution will work for YouTube, but won't necessarily for bad websites.

There will always be edge cases and I don't believe this would introduce any.

The current format selection is arguably worse than youtube-dl's default `bestvideo+bestaudio/best` in a general purpose context, making many assumptions on which formats are better.
Very few sites have multiple formats available for the same resolution, they're even less likely to serve either vp9/av1 streams + a better stream of some other format.
I have checked against Dailymotion and Crunchyroll so far, they return the same stream with the current and my proposed `--format`.

This script as it is currently is very much YouTube-centric, as `--add-metadata` will override original metadata embedded in the video file such as Movie name, Encoded date and Tagged date for services that provide it (e.g. Dailymotion), none of these are present in the `.info.json` and that metadata is just lost.
All metadata added by `--add-metadata` can already be found in `.info.json` and it does more harm that good on non-YouTube sites.

In any case, if adding a way to tweak which formats are preferred, or having presets for different sites; I believe it should be done through a script that generates these `--format` constraints to avoid user error.

> I believe you but I guess since it's a "new" format it might still be good to use it. I don't really know.

YouTube's SDR av1 encodes are impressive, and I totally agree it should be the main format to go for in the future.
I understand the "future proofing" argument but this is something you should not tolerate if downloading in the name of preservation.
av1 encodes of older videos will be made and many of your archives will eventually be obsolete, why not download the best format that is currently available? Nothing is gained by just waiting imho.
The script can be updated when needed, and someday YouTube's encode settings will be updated, or an even better format will be released requiring more tweaks to the script.

I encourage you to make your own comparisons, here are some videos:
[8K with SDR av1 stream](https://www.youtube.com/watch?v=m1jY2VLCRmY)
[4K with HDR av1 stream](https://www.youtube.com/watch?v=6TOEWPDrnwQ)

**Comment by po5** [comment]
Found something else that was only accounted for on YouTube streams: picking 60fps over 30fps.
This doesn't apply when video and audio are a single stream.

Fixed:
`--format '(bestvideo[vcodec=vp9.2][fps>30]/bestvideo[vcodec^=av01][vcodec!$=.0][fps>30]/bestvideo[vcodec^=vp9][fps>30]/bestvideo[vcodec^=av01][fps>30]/bestvideo[fps>30]/bestvideo[vcodec=vp9.2]/bestvideo[vcodec^=av01][vcodec!$=.0]/bestvideo[vcodec^=vp9]/bestvideo[vcodec^=av01]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)/best[fps>30]/best'`

**Comment by TheFrenchGhosty** [comment]
Good to know, I will fix that later.

**Comment by po5** [comment]
On the HDR av1 avoidance:
I've actually never seen a video with an av1 stream where a vp9.2 one was not present, but it's good to have if that ever happens.

In trying to unbloat the format selection and making it more site-agnostic I looked into getting rid of `bestaudio[acodec=opus]` as I'd only ever seen opus streams with a higher bitrate than aac.
It turns out that an opus stream can have a lower reported bitrate than aac as can be seen with this video: https://www.youtube.com/watch?v=YvhVrdUVxyY

Since higher bitrate doesn't necessarily mean better quality and opus is supposed to be efficient at low bitrates I think it should be kept as is, too.

**Comment by github-account1111** [comment]
>Your solution will work for YouTube, but won't necessarily for bad websites.

Does your script even work as intended with other websites? From what I can see there's no mention of, say, `hevc` - a codec that, for example, Vimeo uses a lot. And Vimeo are pretty big. And there are many big websites other than YouTube that combined might even be bigger than YouTube.
